# Generated by Django 4.0.1 on 2022-01-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
