# Generated by Django 4.0.1 on 2022-01-27 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invo', '0002_alter_customer_createddate_alter_invoice_createddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField()),
                ('itemDescription', models.CharField(max_length=1000)),
                ('unit', models.CharField(max_length=20)),
                ('unitPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxCode', models.IntegerField()),
                ('finalAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoiceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invo.invoice')),
            ],
        ),
    ]
