# Generated by Django 4.0.1 on 2022-01-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invo', '0003_invoiceitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, default='bg', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
