# Generated by Django 4.0.1 on 2022-01-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invo', '0004_alter_customer_email_alter_invoiceitem_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='amount',
            new_name='_amount',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='dueBy',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='_amount',
            field=models.DecimalField(db_column='amount', decimal_places=2, max_digits=10),
        ),
    ]
