# Generated by Django 4.0.1 on 2022-01-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invo', '0007_company_rename_amount_invoiceitem__amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxCodes',
            fields=[
                ('taxCode', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('taxPercent', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='taxCode',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='taxCode',
            field=models.ManyToManyField(to='invo.TaxCodes'),
        ),
    ]
