# Generated by Django 4.0.1 on 2022-01-27 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invo', '0008_taxcodes_remove_invoiceitem_taxcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='_amount',
        ),
    ]
