# Generated by Django 4.0.1 on 2022-01-27 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invo', '0009_remove_invoiceitem__amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='subTotal',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='taxName1',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='taxName2',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='taxName3',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='totalTax1',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='totalTax2',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='totalTax3',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='unit',
        ),
    ]
