# Generated by Django 4.0.1 on 2022-01-27 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invo', '0010_remove_invoice_discount_remove_invoice_subtotal_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('-date', 'invoiceID')},
        ),
    ]
