# Generated by Django 4.0.1 on 2022-01-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invo', '0012_invoice_subtotal_invoice_taxname1_invoice_taxname2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='subTotal',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='taxName1',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='taxName2',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='taxName3',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='totalTax1',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='totalTax2',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='totalTax3',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='taxCode',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='taxCode',
            field=models.IntegerField(choices=[(0, 'Btw0'), (6, 'Btw6'), (21, 'Btw21')], default=0),
            preserve_default=False,
        ),
    ]
